input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [level] {
    mutate {
      add_field => { "[@metadata][level]" => "%{level}" }
    }
  }
  if [context] == "http" {
    mutate {
      add_field => { "[@metadata][http]" => true }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "teamshare-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
